name: Build and Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web version
        run: npm run build:web
      
      - name: Upload web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist/ 