name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  docker-compose:
    runs-on: self-hosted
    steps:
      - name: Docker stop old container
        run: docker container stop aegis || true

      - name: Build Docker Image
        run: docker build -t aegis .

      - name: Docker Compose Up
        run: docker run -d --name aegis-fe -p 8081:8081 --rm aegis
